services:
  - type: static
    name: fazaa-landing-page
    buildCommand: "npm run build"
    staticPublishPath: dist
    envVars: []
    routes:
      - type: rewrite
        from: /*
        destination: /index.html
